
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("44a0827f-a7c7-4a17-908d-d872ecd2514c")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("NNeumaticosModel", "FK__Factura__cliente__5CD6CB2B", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Cliente), "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Factura), True)>
<Assembly: EdmRelationshipAttribute("NNeumaticosModel", "FK__Producto__Datos___66603565", "Datos_Tecnicos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Datos_Tecnicos), "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Producto), True)>
<Assembly: EdmRelationshipAttribute("NNeumaticosModel", "FK__Detalle__factura__6B24EA82", "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Factura), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Detalle), True)>
<Assembly: EdmRelationshipAttribute("NNeumaticosModel", "FK__Detalle__product__6C190EBB", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Producto), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Detalle), True)>
<Assembly: EdmRelationshipAttribute("NNeumaticosModel", "FK__Factura__empresa__5DCAEF64", "Empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Empresa), "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Factura), True)>

#End Region

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class NNeumaticosEntities1
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Inicializa un nuevo objeto NNeumaticosEntities1 usando la cadena de conexión encontrada en la sección 'NNeumaticosEntities1' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=NNeumaticosEntities1", "NNeumaticosEntities1")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto NNeumaticosEntities1.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "NNeumaticosEntities1")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto NNeumaticosEntities1.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "NNeumaticosEntities1")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Cliente() As ObjectSet(Of Cliente)
        Get
            If (_Cliente Is Nothing) Then
                _Cliente = MyBase.CreateObjectSet(Of Cliente)("Cliente")
            End If
            Return _Cliente
        End Get
    End Property

    Private _Cliente As ObjectSet(Of Cliente)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Datos_Tecnicos() As ObjectSet(Of Datos_Tecnicos)
        Get
            If (_Datos_Tecnicos Is Nothing) Then
                _Datos_Tecnicos = MyBase.CreateObjectSet(Of Datos_Tecnicos)("Datos_Tecnicos")
            End If
            Return _Datos_Tecnicos
        End Get
    End Property

    Private _Datos_Tecnicos As ObjectSet(Of Datos_Tecnicos)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Detalle() As ObjectSet(Of Detalle)
        Get
            If (_Detalle Is Nothing) Then
                _Detalle = MyBase.CreateObjectSet(Of Detalle)("Detalle")
            End If
            Return _Detalle
        End Get
    End Property

    Private _Detalle As ObjectSet(Of Detalle)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Empresa() As ObjectSet(Of Empresa)
        Get
            If (_Empresa Is Nothing) Then
                _Empresa = MyBase.CreateObjectSet(Of Empresa)("Empresa")
            End If
            Return _Empresa
        End Get
    End Property

    Private _Empresa As ObjectSet(Of Empresa)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Factura() As ObjectSet(Of Factura)
        Get
            If (_Factura Is Nothing) Then
                _Factura = MyBase.CreateObjectSet(Of Factura)("Factura")
            End If
            Return _Factura
        End Get
    End Property

    Private _Factura As ObjectSet(Of Factura)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Producto() As ObjectSet(Of Producto)
        Get
            If (_Producto Is Nothing) Then
                _Producto = MyBase.CreateObjectSet(Of Producto)("Producto")
            End If
            Return _Producto
        End Get
    End Property

    Private _Producto As ObjectSet(Of Producto)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property Usuario() As ObjectSet(Of Usuario)
        Get
            If (_Usuario Is Nothing) Then
                _Usuario = MyBase.CreateObjectSet(Of Usuario)("Usuario")
            End If
            Return _Usuario
        End Get
    End Property

    Private _Usuario As ObjectSet(Of Usuario)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property sysdiagrams() As ObjectSet(Of sysdiagrams)
        Get
            If (_sysdiagrams Is Nothing) Then
                _sysdiagrams = MyBase.CreateObjectSet(Of sysdiagrams)("sysdiagrams")
            End If
            Return _sysdiagrams
        End Get
    End Property

    Private _sysdiagrams As ObjectSet(Of sysdiagrams)

    #End Region
    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Cliente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToCliente(ByVal cliente As Cliente)
        MyBase.AddObject("Cliente", cliente)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Datos_Tecnicos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToDatos_Tecnicos(ByVal datos_Tecnicos As Datos_Tecnicos)
        MyBase.AddObject("Datos_Tecnicos", datos_Tecnicos)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Detalle. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToDetalle(ByVal detalle As Detalle)
        MyBase.AddObject("Detalle", detalle)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Empresa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToEmpresa(ByVal empresa As Empresa)
        MyBase.AddObject("Empresa", empresa)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Factura. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToFactura(ByVal factura As Factura)
        MyBase.AddObject("Factura", factura)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Producto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToProducto(ByVal producto As Producto)
        MyBase.AddObject("Producto", producto)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToUsuario(ByVal usuario As Usuario)
        MyBase.AddObject("Usuario", usuario)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddTosysdiagrams(ByVal sysdiagrams As sysdiagrams)
        MyBase.AddObject("sysdiagrams", sysdiagrams)
    End Sub

    #End Region
    #Region "Importaciones de funciones"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    ''' <param name="ruta">No hay documentación de metadatos disponible.</param>
    Public Function Backup(ruta As Global.System.String) As Integer
        Dim rutaParameter As ObjectParameter
        If (ruta IsNot Nothing)
            rutaParameter = New ObjectParameter("ruta", ruta)
        Else
            rutaParameter = New ObjectParameter("ruta", GetType(Global.System.String))
        End If

        Return MyBase.ExecuteFunction("Backup", rutaParameter)

    End Function

    #End Region
End Class

#End Region
#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="Cliente")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Cliente
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Cliente.
    ''' </summary>
    ''' <param name="cliente_cuil">Valor inicial de la propiedad cliente_cuil.</param>
    ''' <param name="cliente_Ape">Valor inicial de la propiedad cliente_Ape.</param>
    ''' <param name="cliente_Localidad">Valor inicial de la propiedad cliente_Localidad.</param>
    ''' <param name="cliente_Provincia">Valor inicial de la propiedad cliente_Provincia.</param>
    ''' <param name="cliente_Fecha">Valor inicial de la propiedad cliente_Fecha.</param>
    ''' <param name="cliente_Cpostal">Valor inicial de la propiedad cliente_Cpostal.</param>
    ''' <param name="cliente_Celular">Valor inicial de la propiedad cliente_Celular.</param>
    Public Shared Function CreateCliente(cliente_cuil As Global.System.Int64, cliente_Ape As Global.System.String, cliente_Localidad As Global.System.String, cliente_Provincia As Global.System.String, cliente_Fecha As Global.System.String, cliente_Cpostal As Global.System.String, cliente_Celular As Global.System.String) As Cliente
        Dim cliente as Cliente = New Cliente
        cliente.cliente_cuil = cliente_cuil
        cliente.cliente_Ape = cliente_Ape
        cliente.cliente_Localidad = cliente_Localidad
        cliente.cliente_Provincia = cliente_Provincia
        cliente.cliente_Fecha = cliente_Fecha
        cliente.cliente_Cpostal = cliente_Cpostal
        cliente.cliente_Celular = cliente_Celular
        Return cliente
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_cuil() As Global.System.Int64
        Get
            Return _cliente_cuil
        End Get
        Set
            If (_cliente_cuil <> Value) Then
                Oncliente_cuilChanging(value)
                ReportPropertyChanging("cliente_cuil")
                _cliente_cuil = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("cliente_cuil")
                Oncliente_cuilChanged()
            End If
        End Set
    End Property

    Private _cliente_cuil As Global.System.Int64
    Private Partial Sub Oncliente_cuilChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub Oncliente_cuilChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cliente_NomYape() As Global.System.String
        Get
            Return _cliente_NomYape
        End Get
        Set
            Oncliente_NomYapeChanging(value)
            ReportPropertyChanging("cliente_NomYape")
            _cliente_NomYape = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("cliente_NomYape")
            Oncliente_NomYapeChanged()
        End Set
    End Property

    Private _cliente_NomYape As Global.System.String
    Private Partial Sub Oncliente_NomYapeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_NomYapeChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cliente_Direccion() As Global.System.String
        Get
            Return _cliente_Direccion
        End Get
        Set
            Oncliente_DireccionChanging(value)
            ReportPropertyChanging("cliente_Direccion")
            _cliente_Direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("cliente_Direccion")
            Oncliente_DireccionChanged()
        End Set
    End Property

    Private _cliente_Direccion As Global.System.String
    Private Partial Sub Oncliente_DireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_DireccionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cliente_Telefono() As Global.System.String
        Get
            Return _cliente_Telefono
        End Get
        Set
            Oncliente_TelefonoChanging(value)
            ReportPropertyChanging("cliente_Telefono")
            _cliente_Telefono = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("cliente_Telefono")
            Oncliente_TelefonoChanged()
        End Set
    End Property

    Private _cliente_Telefono As Global.System.String
    Private Partial Sub Oncliente_TelefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_TelefonoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cliente_Email() As Global.System.String
        Get
            Return _cliente_Email
        End Get
        Set
            Oncliente_EmailChanging(value)
            ReportPropertyChanging("cliente_Email")
            _cliente_Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("cliente_Email")
            Oncliente_EmailChanged()
        End Set
    End Property

    Private _cliente_Email As Global.System.String
    Private Partial Sub Oncliente_EmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_EmailChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cliente_estado() As Global.System.String
        Get
            Return _cliente_estado
        End Get
        Set
            Oncliente_estadoChanging(value)
            ReportPropertyChanging("cliente_estado")
            _cliente_estado = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("cliente_estado")
            Oncliente_estadoChanged()
        End Set
    End Property

    Private _cliente_estado As Global.System.String
    Private Partial Sub Oncliente_estadoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_estadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_Ape() As Global.System.String
        Get
            Return _cliente_Ape
        End Get
        Set
            Oncliente_ApeChanging(value)
            ReportPropertyChanging("cliente_Ape")
            _cliente_Ape = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("cliente_Ape")
            Oncliente_ApeChanged()
        End Set
    End Property

    Private _cliente_Ape As Global.System.String
    Private Partial Sub Oncliente_ApeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_ApeChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_Localidad() As Global.System.String
        Get
            Return _cliente_Localidad
        End Get
        Set
            Oncliente_LocalidadChanging(value)
            ReportPropertyChanging("cliente_Localidad")
            _cliente_Localidad = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("cliente_Localidad")
            Oncliente_LocalidadChanged()
        End Set
    End Property

    Private _cliente_Localidad As Global.System.String
    Private Partial Sub Oncliente_LocalidadChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_LocalidadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_Provincia() As Global.System.String
        Get
            Return _cliente_Provincia
        End Get
        Set
            Oncliente_ProvinciaChanging(value)
            ReportPropertyChanging("cliente_Provincia")
            _cliente_Provincia = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("cliente_Provincia")
            Oncliente_ProvinciaChanged()
        End Set
    End Property

    Private _cliente_Provincia As Global.System.String
    Private Partial Sub Oncliente_ProvinciaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_ProvinciaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_Fecha() As Global.System.String
        Get
            Return _cliente_Fecha
        End Get
        Set
            Oncliente_FechaChanging(value)
            ReportPropertyChanging("cliente_Fecha")
            _cliente_Fecha = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("cliente_Fecha")
            Oncliente_FechaChanged()
        End Set
    End Property

    Private _cliente_Fecha As Global.System.String
    Private Partial Sub Oncliente_FechaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_FechaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_Cpostal() As Global.System.String
        Get
            Return _cliente_Cpostal
        End Get
        Set
            Oncliente_CpostalChanging(value)
            ReportPropertyChanging("cliente_Cpostal")
            _cliente_Cpostal = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("cliente_Cpostal")
            Oncliente_CpostalChanged()
        End Set
    End Property

    Private _cliente_Cpostal As Global.System.String
    Private Partial Sub Oncliente_CpostalChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_CpostalChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_Celular() As Global.System.String
        Get
            Return _cliente_Celular
        End Get
        Set
            Oncliente_CelularChanging(value)
            ReportPropertyChanging("cliente_Celular")
            _cliente_Celular = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("cliente_Celular")
            Oncliente_CelularChanged()
        End Set
    End Property

    Private _cliente_Celular As Global.System.String
    Private Partial Sub Oncliente_CelularChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Oncliente_CelularChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Factura__cliente__5CD6CB2B", "Factura")>
     Public Property Factura() As EntityCollection(Of Factura)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Factura)("NNeumaticosModel.FK__Factura__cliente__5CD6CB2B", "Factura")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Factura)("NNeumaticosModel.FK__Factura__cliente__5CD6CB2B", "Factura", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="Datos_Tecnicos")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Datos_Tecnicos
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Datos_Tecnicos.
    ''' </summary>
    ''' <param name="datos_cod">Valor inicial de la propiedad Datos_cod.</param>
    ''' <param name="datos_Medida">Valor inicial de la propiedad Datos_Medida.</param>
    ''' <param name="datos_IndCarga">Valor inicial de la propiedad Datos_IndCarga.</param>
    ''' <param name="datos_RevPorKm">Valor inicial de la propiedad Datos_RevPorKm.</param>
    ''' <param name="datos_AnchoLLanta">Valor inicial de la propiedad Datos_AnchoLLanta.</param>
    ''' <param name="datos_AnchoSecion">Valor inicial de la propiedad Datos_AnchoSecion.</param>
    ''' <param name="datos_Diametro">Valor inicial de la propiedad Datos_Diametro.</param>
    Public Shared Function CreateDatos_Tecnicos(datos_cod As Global.System.Int32, datos_Medida As Global.System.String, datos_IndCarga As Global.System.Int32, datos_RevPorKm As Global.System.Int32, datos_AnchoLLanta As Global.System.Double, datos_AnchoSecion As Global.System.Int32, datos_Diametro As Global.System.Int32) As Datos_Tecnicos
        Dim datos_Tecnicos as Datos_Tecnicos = New Datos_Tecnicos
        datos_Tecnicos.Datos_cod = datos_cod
        datos_Tecnicos.Datos_Medida = datos_Medida
        datos_Tecnicos.Datos_IndCarga = datos_IndCarga
        datos_Tecnicos.Datos_RevPorKm = datos_RevPorKm
        datos_Tecnicos.Datos_AnchoLLanta = datos_AnchoLLanta
        datos_Tecnicos.Datos_AnchoSecion = datos_AnchoSecion
        datos_Tecnicos.Datos_Diametro = datos_Diametro
        Return datos_Tecnicos
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_cod() As Global.System.Int32
        Get
            Return _Datos_cod
        End Get
        Set
            If (_Datos_cod <> Value) Then
                OnDatos_codChanging(value)
                ReportPropertyChanging("Datos_cod")
                _Datos_cod = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Datos_cod")
                OnDatos_codChanged()
            End If
        End Set
    End Property

    Private _Datos_cod As Global.System.Int32
    Private Partial Sub OnDatos_codChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDatos_codChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_Medida() As Global.System.String
        Get
            Return _Datos_Medida
        End Get
        Set
            OnDatos_MedidaChanging(value)
            ReportPropertyChanging("Datos_Medida")
            _Datos_Medida = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Datos_Medida")
            OnDatos_MedidaChanged()
        End Set
    End Property

    Private _Datos_Medida As Global.System.String
    Private Partial Sub OnDatos_MedidaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDatos_MedidaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_IndCarga() As Global.System.Int32
        Get
            Return _Datos_IndCarga
        End Get
        Set
            OnDatos_IndCargaChanging(value)
            ReportPropertyChanging("Datos_IndCarga")
            _Datos_IndCarga = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Datos_IndCarga")
            OnDatos_IndCargaChanged()
        End Set
    End Property

    Private _Datos_IndCarga As Global.System.Int32
    Private Partial Sub OnDatos_IndCargaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDatos_IndCargaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Datos_Velocidad() As Global.System.String
        Get
            Return _Datos_Velocidad
        End Get
        Set
            OnDatos_VelocidadChanging(value)
            ReportPropertyChanging("Datos_Velocidad")
            _Datos_Velocidad = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Datos_Velocidad")
            OnDatos_VelocidadChanged()
        End Set
    End Property

    Private _Datos_Velocidad As Global.System.String
    Private Partial Sub OnDatos_VelocidadChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDatos_VelocidadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_RevPorKm() As Global.System.Int32
        Get
            Return _Datos_RevPorKm
        End Get
        Set
            OnDatos_RevPorKmChanging(value)
            ReportPropertyChanging("Datos_RevPorKm")
            _Datos_RevPorKm = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Datos_RevPorKm")
            OnDatos_RevPorKmChanged()
        End Set
    End Property

    Private _Datos_RevPorKm As Global.System.Int32
    Private Partial Sub OnDatos_RevPorKmChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDatos_RevPorKmChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_AnchoLLanta() As Global.System.Double
        Get
            Return _Datos_AnchoLLanta
        End Get
        Set
            OnDatos_AnchoLLantaChanging(value)
            ReportPropertyChanging("Datos_AnchoLLanta")
            _Datos_AnchoLLanta = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Datos_AnchoLLanta")
            OnDatos_AnchoLLantaChanged()
        End Set
    End Property

    Private _Datos_AnchoLLanta As Global.System.Double
    Private Partial Sub OnDatos_AnchoLLantaChanging(value As Global.System.Double)
    End Sub

    Private Partial Sub OnDatos_AnchoLLantaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_AnchoSecion() As Global.System.Int32
        Get
            Return _Datos_AnchoSecion
        End Get
        Set
            OnDatos_AnchoSecionChanging(value)
            ReportPropertyChanging("Datos_AnchoSecion")
            _Datos_AnchoSecion = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Datos_AnchoSecion")
            OnDatos_AnchoSecionChanged()
        End Set
    End Property

    Private _Datos_AnchoSecion As Global.System.Int32
    Private Partial Sub OnDatos_AnchoSecionChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDatos_AnchoSecionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_Diametro() As Global.System.Int32
        Get
            Return _Datos_Diametro
        End Get
        Set
            OnDatos_DiametroChanging(value)
            ReportPropertyChanging("Datos_Diametro")
            _Datos_Diametro = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Datos_Diametro")
            OnDatos_DiametroChanged()
        End Set
    End Property

    Private _Datos_Diametro As Global.System.Int32
    Private Partial Sub OnDatos_DiametroChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDatos_DiametroChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Producto__Datos___66603565", "Producto")>
     Public Property Producto() As EntityCollection(Of Producto)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Producto)("NNeumaticosModel.FK__Producto__Datos___66603565", "Producto")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Producto)("NNeumaticosModel.FK__Producto__Datos___66603565", "Producto", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="Detalle")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Detalle
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Detalle.
    ''' </summary>
    ''' <param name="detalle_id">Valor inicial de la propiedad detalle_id.</param>
    ''' <param name="factura_num">Valor inicial de la propiedad factura_num.</param>
    ''' <param name="producto_id">Valor inicial de la propiedad producto_id.</param>
    ''' <param name="detalle_cantidad">Valor inicial de la propiedad detalle_cantidad.</param>
    ''' <param name="detalle_total">Valor inicial de la propiedad detalle_total.</param>
    Public Shared Function CreateDetalle(detalle_id As Global.System.Int32, factura_num As Global.System.Int32, producto_id As Global.System.Int32, detalle_cantidad As Global.System.Int32, detalle_total As Global.System.Double) As Detalle
        Dim detalle as Detalle = New Detalle
        detalle.detalle_id = detalle_id
        detalle.factura_num = factura_num
        detalle.producto_id = producto_id
        detalle.detalle_cantidad = detalle_cantidad
        detalle.detalle_total = detalle_total
        Return detalle
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property detalle_id() As Global.System.Int32
        Get
            Return _detalle_id
        End Get
        Set
            If (_detalle_id <> Value) Then
                Ondetalle_idChanging(value)
                ReportPropertyChanging("detalle_id")
                _detalle_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("detalle_id")
                Ondetalle_idChanged()
            End If
        End Set
    End Property

    Private _detalle_id As Global.System.Int32
    Private Partial Sub Ondetalle_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondetalle_idChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property factura_num() As Global.System.Int32
        Get
            Return _factura_num
        End Get
        Set
            If (_factura_num <> Value) Then
                Onfactura_numChanging(value)
                ReportPropertyChanging("factura_num")
                _factura_num = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("factura_num")
                Onfactura_numChanged()
            End If
        End Set
    End Property

    Private _factura_num As Global.System.Int32
    Private Partial Sub Onfactura_numChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onfactura_numChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property producto_id() As Global.System.Int32
        Get
            Return _producto_id
        End Get
        Set
            Onproducto_idChanging(value)
            ReportPropertyChanging("producto_id")
            _producto_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("producto_id")
            Onproducto_idChanged()
        End Set
    End Property

    Private _producto_id As Global.System.Int32
    Private Partial Sub Onproducto_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onproducto_idChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property detalle_cantidad() As Global.System.Int32
        Get
            Return _detalle_cantidad
        End Get
        Set
            Ondetalle_cantidadChanging(value)
            ReportPropertyChanging("detalle_cantidad")
            _detalle_cantidad = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("detalle_cantidad")
            Ondetalle_cantidadChanged()
        End Set
    End Property

    Private _detalle_cantidad As Global.System.Int32
    Private Partial Sub Ondetalle_cantidadChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondetalle_cantidadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property detalle_precio() As Nullable(Of Global.System.Double)
        Get
            Return _detalle_precio
        End Get
        Set
            Ondetalle_precioChanging(value)
            ReportPropertyChanging("detalle_precio")
            _detalle_precio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("detalle_precio")
            Ondetalle_precioChanged()
        End Set
    End Property

    Private _detalle_precio As Nullable(Of Global.System.Double)
    Private Partial Sub Ondetalle_precioChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub Ondetalle_precioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property detalle_total() As Global.System.Double
        Get
            Return _detalle_total
        End Get
        Set
            Ondetalle_totalChanging(value)
            ReportPropertyChanging("detalle_total")
            _detalle_total = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("detalle_total")
            Ondetalle_totalChanged()
        End Set
    End Property

    Private _detalle_total As Global.System.Double
    Private Partial Sub Ondetalle_totalChanging(value As Global.System.Double)
    End Sub

    Private Partial Sub Ondetalle_totalChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Detalle__factura__6B24EA82", "Factura")>
    Public Property Factura() As Factura
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("NNeumaticosModel.FK__Detalle__factura__6B24EA82", "Factura").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("NNeumaticosModel.FK__Detalle__factura__6B24EA82", "Factura").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property FacturaReference() As EntityReference(Of Factura)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("NNeumaticosModel.FK__Detalle__factura__6B24EA82", "Factura")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Factura)("NNeumaticosModel.FK__Detalle__factura__6B24EA82", "Factura", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Detalle__product__6C190EBB", "Producto")>
    Public Property Producto() As Producto
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("NNeumaticosModel.FK__Detalle__product__6C190EBB", "Producto").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("NNeumaticosModel.FK__Detalle__product__6C190EBB", "Producto").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductoReference() As EntityReference(Of Producto)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("NNeumaticosModel.FK__Detalle__product__6C190EBB", "Producto")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Producto)("NNeumaticosModel.FK__Detalle__product__6C190EBB", "Producto", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="Empresa")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Empresa
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Empresa.
    ''' </summary>
    ''' <param name="empresa_cuit">Valor inicial de la propiedad empresa_cuit.</param>
    ''' <param name="empresa_nombre">Valor inicial de la propiedad empresa_nombre.</param>
    ''' <param name="empresa_direccion">Valor inicial de la propiedad empresa_direccion.</param>
    ''' <param name="empresa_email">Valor inicial de la propiedad empresa_email.</param>
    ''' <param name="empresa_telefono">Valor inicial de la propiedad empresa_telefono.</param>
    Public Shared Function CreateEmpresa(empresa_cuit As Global.System.Int64, empresa_nombre As Global.System.String, empresa_direccion As Global.System.String, empresa_email As Global.System.String, empresa_telefono As Global.System.String) As Empresa
        Dim empresa as Empresa = New Empresa
        empresa.empresa_cuit = empresa_cuit
        empresa.empresa_nombre = empresa_nombre
        empresa.empresa_direccion = empresa_direccion
        empresa.empresa_email = empresa_email
        empresa.empresa_telefono = empresa_telefono
        Return empresa
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property empresa_cuit() As Global.System.Int64
        Get
            Return _empresa_cuit
        End Get
        Set
            If (_empresa_cuit <> Value) Then
                Onempresa_cuitChanging(value)
                ReportPropertyChanging("empresa_cuit")
                _empresa_cuit = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("empresa_cuit")
                Onempresa_cuitChanged()
            End If
        End Set
    End Property

    Private _empresa_cuit As Global.System.Int64
    Private Partial Sub Onempresa_cuitChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub Onempresa_cuitChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property empresa_nombre() As Global.System.String
        Get
            Return _empresa_nombre
        End Get
        Set
            Onempresa_nombreChanging(value)
            ReportPropertyChanging("empresa_nombre")
            _empresa_nombre = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("empresa_nombre")
            Onempresa_nombreChanged()
        End Set
    End Property

    Private _empresa_nombre As Global.System.String
    Private Partial Sub Onempresa_nombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onempresa_nombreChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property empresa_direccion() As Global.System.String
        Get
            Return _empresa_direccion
        End Get
        Set
            Onempresa_direccionChanging(value)
            ReportPropertyChanging("empresa_direccion")
            _empresa_direccion = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("empresa_direccion")
            Onempresa_direccionChanged()
        End Set
    End Property

    Private _empresa_direccion As Global.System.String
    Private Partial Sub Onempresa_direccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onempresa_direccionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property empresa_email() As Global.System.String
        Get
            Return _empresa_email
        End Get
        Set
            Onempresa_emailChanging(value)
            ReportPropertyChanging("empresa_email")
            _empresa_email = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("empresa_email")
            Onempresa_emailChanged()
        End Set
    End Property

    Private _empresa_email As Global.System.String
    Private Partial Sub Onempresa_emailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onempresa_emailChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property empresa_telefono() As Global.System.String
        Get
            Return _empresa_telefono
        End Get
        Set
            Onempresa_telefonoChanging(value)
            ReportPropertyChanging("empresa_telefono")
            _empresa_telefono = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("empresa_telefono")
            Onempresa_telefonoChanged()
        End Set
    End Property

    Private _empresa_telefono As Global.System.String
    Private Partial Sub Onempresa_telefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onempresa_telefonoChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Factura__empresa__5DCAEF64", "Factura")>
     Public Property Factura() As EntityCollection(Of Factura)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Factura)("NNeumaticosModel.FK__Factura__empresa__5DCAEF64", "Factura")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Factura)("NNeumaticosModel.FK__Factura__empresa__5DCAEF64", "Factura", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="Factura")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Factura
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Factura.
    ''' </summary>
    ''' <param name="factura_num">Valor inicial de la propiedad factura_num.</param>
    ''' <param name="cliente_cuil">Valor inicial de la propiedad cliente_cuil.</param>
    ''' <param name="empresa_cuit">Valor inicial de la propiedad empresa_cuit.</param>
    ''' <param name="factura_Fecha">Valor inicial de la propiedad factura_Fecha.</param>
    ''' <param name="factura_Total">Valor inicial de la propiedad factura_Total.</param>
    Public Shared Function CreateFactura(factura_num As Global.System.Int32, cliente_cuil As Global.System.Int64, empresa_cuit As Global.System.Int64, factura_Fecha As Global.System.DateTime, factura_Total As Global.System.Double) As Factura
        Dim factura as Factura = New Factura
        factura.factura_num = factura_num
        factura.cliente_cuil = cliente_cuil
        factura.empresa_cuit = empresa_cuit
        factura.factura_Fecha = factura_Fecha
        factura.factura_Total = factura_Total
        Return factura
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property factura_num() As Global.System.Int32
        Get
            Return _factura_num
        End Get
        Set
            If (_factura_num <> Value) Then
                Onfactura_numChanging(value)
                ReportPropertyChanging("factura_num")
                _factura_num = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("factura_num")
                Onfactura_numChanged()
            End If
        End Set
    End Property

    Private _factura_num As Global.System.Int32
    Private Partial Sub Onfactura_numChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onfactura_numChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property cliente_cuil() As Global.System.Int64
        Get
            Return _cliente_cuil
        End Get
        Set
            Oncliente_cuilChanging(value)
            ReportPropertyChanging("cliente_cuil")
            _cliente_cuil = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cliente_cuil")
            Oncliente_cuilChanged()
        End Set
    End Property

    Private _cliente_cuil As Global.System.Int64
    Private Partial Sub Oncliente_cuilChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub Oncliente_cuilChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property empresa_cuit() As Global.System.Int64
        Get
            Return _empresa_cuit
        End Get
        Set
            Onempresa_cuitChanging(value)
            ReportPropertyChanging("empresa_cuit")
            _empresa_cuit = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("empresa_cuit")
            Onempresa_cuitChanged()
        End Set
    End Property

    Private _empresa_cuit As Global.System.Int64
    Private Partial Sub Onempresa_cuitChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub Onempresa_cuitChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property factura_Fecha() As Global.System.DateTime
        Get
            Return _factura_Fecha
        End Get
        Set
            Onfactura_FechaChanging(value)
            ReportPropertyChanging("factura_Fecha")
            _factura_Fecha = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("factura_Fecha")
            Onfactura_FechaChanged()
        End Set
    End Property

    Private _factura_Fecha As Global.System.DateTime
    Private Partial Sub Onfactura_FechaChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub Onfactura_FechaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property factura_tipoPago() As Global.System.String
        Get
            Return _factura_tipoPago
        End Get
        Set
            Onfactura_tipoPagoChanging(value)
            ReportPropertyChanging("factura_tipoPago")
            _factura_tipoPago = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("factura_tipoPago")
            Onfactura_tipoPagoChanged()
        End Set
    End Property

    Private _factura_tipoPago As Global.System.String
    Private Partial Sub Onfactura_tipoPagoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onfactura_tipoPagoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property factura_estado() As Global.System.String
        Get
            Return _factura_estado
        End Get
        Set
            Onfactura_estadoChanging(value)
            ReportPropertyChanging("factura_estado")
            _factura_estado = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("factura_estado")
            Onfactura_estadoChanged()
        End Set
    End Property

    Private _factura_estado As Global.System.String
    Private Partial Sub Onfactura_estadoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onfactura_estadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property factura_Total() As Global.System.Double
        Get
            Return _factura_Total
        End Get
        Set
            Onfactura_TotalChanging(value)
            ReportPropertyChanging("factura_Total")
            _factura_Total = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("factura_Total")
            Onfactura_TotalChanged()
        End Set
    End Property

    Private _factura_Total As Global.System.Double
    Private Partial Sub Onfactura_TotalChanging(value As Global.System.Double)
    End Sub

    Private Partial Sub Onfactura_TotalChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property factura_vendedor() As Nullable(Of Global.System.Int32)
        Get
            Return _factura_vendedor
        End Get
        Set
            Onfactura_vendedorChanging(value)
            ReportPropertyChanging("factura_vendedor")
            _factura_vendedor = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("factura_vendedor")
            Onfactura_vendedorChanged()
        End Set
    End Property

    Private _factura_vendedor As Nullable(Of Global.System.Int32)
    Private Partial Sub Onfactura_vendedorChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onfactura_vendedorChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Factura__cliente__5CD6CB2B", "Cliente")>
    Public Property Cliente() As Cliente
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cliente)("NNeumaticosModel.FK__Factura__cliente__5CD6CB2B", "Cliente").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cliente)("NNeumaticosModel.FK__Factura__cliente__5CD6CB2B", "Cliente").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ClienteReference() As EntityReference(Of Cliente)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cliente)("NNeumaticosModel.FK__Factura__cliente__5CD6CB2B", "Cliente")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Cliente)("NNeumaticosModel.FK__Factura__cliente__5CD6CB2B", "Cliente", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Detalle__factura__6B24EA82", "Detalle")>
     Public Property Detalle() As EntityCollection(Of Detalle)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Detalle)("NNeumaticosModel.FK__Detalle__factura__6B24EA82", "Detalle")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Detalle)("NNeumaticosModel.FK__Detalle__factura__6B24EA82", "Detalle", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Factura__empresa__5DCAEF64", "Empresa")>
    Public Property Empresa() As Empresa
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Empresa)("NNeumaticosModel.FK__Factura__empresa__5DCAEF64", "Empresa").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Empresa)("NNeumaticosModel.FK__Factura__empresa__5DCAEF64", "Empresa").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property EmpresaReference() As EntityReference(Of Empresa)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Empresa)("NNeumaticosModel.FK__Factura__empresa__5DCAEF64", "Empresa")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Empresa)("NNeumaticosModel.FK__Factura__empresa__5DCAEF64", "Empresa", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="Producto")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Producto
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Producto.
    ''' </summary>
    ''' <param name="producto_id">Valor inicial de la propiedad producto_id.</param>
    ''' <param name="producto_nombre">Valor inicial de la propiedad producto_nombre.</param>
    ''' <param name="producto_rodado">Valor inicial de la propiedad producto_rodado.</param>
    ''' <param name="producto_medida">Valor inicial de la propiedad producto_medida.</param>
    ''' <param name="producto_precio">Valor inicial de la propiedad producto_precio.</param>
    ''' <param name="datos_cod">Valor inicial de la propiedad Datos_cod.</param>
    ''' <param name="producto_stock">Valor inicial de la propiedad producto_stock.</param>
    Public Shared Function CreateProducto(producto_id As Global.System.Int32, producto_nombre As Global.System.String, producto_rodado As Global.System.String, producto_medida As Global.System.String, producto_precio As Global.System.Double, datos_cod As Global.System.Int32, producto_stock As Global.System.Int32) As Producto
        Dim producto as Producto = New Producto
        producto.producto_id = producto_id
        producto.producto_nombre = producto_nombre
        producto.producto_rodado = producto_rodado
        producto.producto_medida = producto_medida
        producto.producto_precio = producto_precio
        producto.Datos_cod = datos_cod
        producto.producto_stock = producto_stock
        Return producto
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property producto_id() As Global.System.Int32
        Get
            Return _producto_id
        End Get
        Set
            If (_producto_id <> Value) Then
                Onproducto_idChanging(value)
                ReportPropertyChanging("producto_id")
                _producto_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("producto_id")
                Onproducto_idChanged()
            End If
        End Set
    End Property

    Private _producto_id As Global.System.Int32
    Private Partial Sub Onproducto_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onproducto_idChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property producto_nombre() As Global.System.String
        Get
            Return _producto_nombre
        End Get
        Set
            Onproducto_nombreChanging(value)
            ReportPropertyChanging("producto_nombre")
            _producto_nombre = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("producto_nombre")
            Onproducto_nombreChanged()
        End Set
    End Property

    Private _producto_nombre As Global.System.String
    Private Partial Sub Onproducto_nombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onproducto_nombreChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property producto_rodado() As Global.System.String
        Get
            Return _producto_rodado
        End Get
        Set
            Onproducto_rodadoChanging(value)
            ReportPropertyChanging("producto_rodado")
            _producto_rodado = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("producto_rodado")
            Onproducto_rodadoChanged()
        End Set
    End Property

    Private _producto_rodado As Global.System.String
    Private Partial Sub Onproducto_rodadoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onproducto_rodadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property producto_medida() As Global.System.String
        Get
            Return _producto_medida
        End Get
        Set
            Onproducto_medidaChanging(value)
            ReportPropertyChanging("producto_medida")
            _producto_medida = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("producto_medida")
            Onproducto_medidaChanged()
        End Set
    End Property

    Private _producto_medida As Global.System.String
    Private Partial Sub Onproducto_medidaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onproducto_medidaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property producto_precio() As Global.System.Double
        Get
            Return _producto_precio
        End Get
        Set
            Onproducto_precioChanging(value)
            ReportPropertyChanging("producto_precio")
            _producto_precio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("producto_precio")
            Onproducto_precioChanged()
        End Set
    End Property

    Private _producto_precio As Global.System.Double
    Private Partial Sub Onproducto_precioChanging(value As Global.System.Double)
    End Sub

    Private Partial Sub Onproducto_precioChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Datos_cod() As Global.System.Int32
        Get
            Return _Datos_cod
        End Get
        Set
            OnDatos_codChanging(value)
            ReportPropertyChanging("Datos_cod")
            _Datos_cod = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Datos_cod")
            OnDatos_codChanged()
        End Set
    End Property

    Private _Datos_cod As Global.System.Int32
    Private Partial Sub OnDatos_codChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDatos_codChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property producto_stock() As Global.System.Int32
        Get
            Return _producto_stock
        End Get
        Set
            Onproducto_stockChanging(value)
            ReportPropertyChanging("producto_stock")
            _producto_stock = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("producto_stock")
            Onproducto_stockChanged()
        End Set
    End Property

    Private _producto_stock As Global.System.Int32
    Private Partial Sub Onproducto_stockChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onproducto_stockChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property producto_imagen() As Global.System.String
        Get
            Return _producto_imagen
        End Get
        Set
            Onproducto_imagenChanging(value)
            ReportPropertyChanging("producto_imagen")
            _producto_imagen = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("producto_imagen")
            Onproducto_imagenChanged()
        End Set
    End Property

    Private _producto_imagen As Global.System.String
    Private Partial Sub Onproducto_imagenChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onproducto_imagenChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property producto_estado() As Global.System.String
        Get
            Return _producto_estado
        End Get
        Set
            Onproducto_estadoChanging(value)
            ReportPropertyChanging("producto_estado")
            _producto_estado = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("producto_estado")
            Onproducto_estadoChanged()
        End Set
    End Property

    Private _producto_estado As Global.System.String
    Private Partial Sub Onproducto_estadoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onproducto_estadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property tipoVehi_descripcion() As Global.System.String
        Get
            Return _tipoVehi_descripcion
        End Get
        Set
            OntipoVehi_descripcionChanging(value)
            ReportPropertyChanging("tipoVehi_descripcion")
            _tipoVehi_descripcion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("tipoVehi_descripcion")
            OntipoVehi_descripcionChanged()
        End Set
    End Property

    Private _tipoVehi_descripcion As Global.System.String
    Private Partial Sub OntipoVehi_descripcionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntipoVehi_descripcionChanged()
    End Sub

    #End Region
    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Producto__Datos___66603565", "Datos_Tecnicos")>
    Public Property Datos_Tecnicos() As Datos_Tecnicos
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Datos_Tecnicos)("NNeumaticosModel.FK__Producto__Datos___66603565", "Datos_Tecnicos").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Datos_Tecnicos)("NNeumaticosModel.FK__Producto__Datos___66603565", "Datos_Tecnicos").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property Datos_TecnicosReference() As EntityReference(Of Datos_Tecnicos)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Datos_Tecnicos)("NNeumaticosModel.FK__Producto__Datos___66603565", "Datos_Tecnicos")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Datos_Tecnicos)("NNeumaticosModel.FK__Producto__Datos___66603565", "Datos_Tecnicos", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("NNeumaticosModel", "FK__Detalle__product__6C190EBB", "Detalle")>
     Public Property Detalle() As EntityCollection(Of Detalle)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Detalle)("NNeumaticosModel.FK__Detalle__product__6C190EBB", "Detalle")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Detalle)("NNeumaticosModel.FK__Detalle__product__6C190EBB", "Detalle", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="sysdiagrams")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class sysdiagrams
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto sysdiagrams.
    ''' </summary>
    ''' <param name="name">Valor inicial de la propiedad name.</param>
    ''' <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
    ''' <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
    Public Shared Function Createsysdiagrams(name As Global.System.String, principal_id As Global.System.Int32, diagram_id As Global.System.Int32) As sysdiagrams
        Dim sysdiagrams as sysdiagrams = New sysdiagrams
        sysdiagrams.name = name
        sysdiagrams.principal_id = principal_id
        sysdiagrams.diagram_id = diagram_id
        Return sysdiagrams
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property principal_id() As Global.System.Int32
        Get
            Return _principal_id
        End Get
        Set
            Onprincipal_idChanging(value)
            ReportPropertyChanging("principal_id")
            _principal_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("principal_id")
            Onprincipal_idChanged()
        End Set
    End Property

    Private _principal_id As Global.System.Int32
    Private Partial Sub Onprincipal_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onprincipal_idChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property diagram_id() As Global.System.Int32
        Get
            Return _diagram_id
        End Get
        Set
            If (_diagram_id <> Value) Then
                Ondiagram_idChanging(value)
                ReportPropertyChanging("diagram_id")
                _diagram_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("diagram_id")
                Ondiagram_idChanged()
            End If
        End Set
    End Property

    Private _diagram_id As Global.System.Int32
    Private Partial Sub Ondiagram_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondiagram_idChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property version() As Nullable(Of Global.System.Int32)
        Get
            Return _version
        End Get
        Set
            OnversionChanging(value)
            ReportPropertyChanging("version")
            _version = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("version")
            OnversionChanged()
        End Set
    End Property

    Private _version As Nullable(Of Global.System.Int32)
    Private Partial Sub OnversionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnversionChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property definition() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_definition)
        End Get
        Set
            OndefinitionChanging(value)
            ReportPropertyChanging("definition")
            _definition = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("definition")
            OndefinitionChanged()
        End Set
    End Property

    Private _definition As Global.System.Byte()
    Private Partial Sub OndefinitionChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OndefinitionChanged()
    End Sub

    #End Region
End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="NNeumaticosModel", Name:="Usuario")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Usuario
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto Usuario.
    ''' </summary>
    ''' <param name="usu_Dni">Valor inicial de la propiedad usu_Dni.</param>
    Public Shared Function CreateUsuario(usu_Dni As Global.System.Int32) As Usuario
        Dim usuario as Usuario = New Usuario
        usuario.usu_Dni = usu_Dni
        Return usuario
    End Function

    #End Region
    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property usu_Dni() As Global.System.Int32
        Get
            Return _usu_Dni
        End Get
        Set
            If (_usu_Dni <> Value) Then
                Onusu_DniChanging(value)
                ReportPropertyChanging("usu_Dni")
                _usu_Dni = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("usu_Dni")
                Onusu_DniChanged()
            End If
        End Set
    End Property

    Private _usu_Dni As Global.System.Int32
    Private Partial Sub Onusu_DniChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onusu_DniChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_nomYape() As Global.System.String
        Get
            Return _usu_nomYape
        End Get
        Set
            Onusu_nomYapeChanging(value)
            ReportPropertyChanging("usu_nomYape")
            _usu_nomYape = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_nomYape")
            Onusu_nomYapeChanged()
        End Set
    End Property

    Private _usu_nomYape As Global.System.String
    Private Partial Sub Onusu_nomYapeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_nomYapeChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Direccon() As Global.System.String
        Get
            Return _usu_Direccon
        End Get
        Set
            Onusu_DirecconChanging(value)
            ReportPropertyChanging("usu_Direccon")
            _usu_Direccon = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Direccon")
            Onusu_DirecconChanged()
        End Set
    End Property

    Private _usu_Direccon As Global.System.String
    Private Partial Sub Onusu_DirecconChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_DirecconChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Localidad() As Global.System.String
        Get
            Return _usu_Localidad
        End Get
        Set
            Onusu_LocalidadChanging(value)
            ReportPropertyChanging("usu_Localidad")
            _usu_Localidad = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Localidad")
            Onusu_LocalidadChanged()
        End Set
    End Property

    Private _usu_Localidad As Global.System.String
    Private Partial Sub Onusu_LocalidadChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_LocalidadChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Provincia() As Global.System.String
        Get
            Return _usu_Provincia
        End Get
        Set
            Onusu_ProvinciaChanging(value)
            ReportPropertyChanging("usu_Provincia")
            _usu_Provincia = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Provincia")
            Onusu_ProvinciaChanged()
        End Set
    End Property

    Private _usu_Provincia As Global.System.String
    Private Partial Sub Onusu_ProvinciaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_ProvinciaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Telefono() As Global.System.String
        Get
            Return _usu_Telefono
        End Get
        Set
            Onusu_TelefonoChanging(value)
            ReportPropertyChanging("usu_Telefono")
            _usu_Telefono = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Telefono")
            Onusu_TelefonoChanged()
        End Set
    End Property

    Private _usu_Telefono As Global.System.String
    Private Partial Sub Onusu_TelefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_TelefonoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Email() As Global.System.String
        Get
            Return _usu_Email
        End Get
        Set
            Onusu_EmailChanging(value)
            ReportPropertyChanging("usu_Email")
            _usu_Email = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Email")
            Onusu_EmailChanged()
        End Set
    End Property

    Private _usu_Email As Global.System.String
    Private Partial Sub Onusu_EmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_EmailChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Contraseña() As Global.System.String
        Get
            Return _usu_Contraseña
        End Get
        Set
            Onusu_ContraseñaChanging(value)
            ReportPropertyChanging("usu_Contraseña")
            _usu_Contraseña = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Contraseña")
            Onusu_ContraseñaChanged()
        End Set
    End Property

    Private _usu_Contraseña As Global.System.String
    Private Partial Sub Onusu_ContraseñaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_ContraseñaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Estado() As Global.System.String
        Get
            Return _usu_Estado
        End Get
        Set
            Onusu_EstadoChanging(value)
            ReportPropertyChanging("usu_Estado")
            _usu_Estado = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Estado")
            Onusu_EstadoChanged()
        End Set
    End Property

    Private _usu_Estado As Global.System.String
    Private Partial Sub Onusu_EstadoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_EstadoChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_TipoUsu() As Global.System.String
        Get
            Return _usu_TipoUsu
        End Get
        Set
            Onusu_TipoUsuChanging(value)
            ReportPropertyChanging("usu_TipoUsu")
            _usu_TipoUsu = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_TipoUsu")
            Onusu_TipoUsuChanged()
        End Set
    End Property

    Private _usu_TipoUsu As Global.System.String
    Private Partial Sub Onusu_TipoUsuChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_TipoUsuChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_Fecha() As Global.System.String
        Get
            Return _usu_Fecha
        End Get
        Set
            Onusu_FechaChanging(value)
            ReportPropertyChanging("usu_Fecha")
            _usu_Fecha = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_Fecha")
            Onusu_FechaChanged()
        End Set
    End Property

    Private _usu_Fecha As Global.System.String
    Private Partial Sub Onusu_FechaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_FechaChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property usu_ape() As Global.System.String
        Get
            Return _usu_ape
        End Get
        Set
            Onusu_apeChanging(value)
            ReportPropertyChanging("usu_ape")
            _usu_ape = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("usu_ape")
            Onusu_apeChanged()
        End Set
    End Property

    Private _usu_ape As Global.System.String
    Private Partial Sub Onusu_apeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onusu_apeChanged()
    End Sub

    #End Region
End Class

#End Region

